### ISSUE TITLE
Change link value to the proper one

### ISSUE THREAD

**Issue by merey90** [merey90/tulenova#36]
**Description**:
The link leads to apply page, whereas it should go to info page.

**AC's**:
- On concerts page, in entry dated `November 19 2022` change link from `https://www.internationale-em-akademie.de/en/apply-now` to `https://www.ensemble-modern.com/de/projekte/de/kalender/2022-11-19/5800#k-5800`

https://github.com/merey90/tulenova/blob/master/src/concerts/index.tsx#L17

**Comment by bloodmonk7** [comment]
Can I do this? Assign it to me please

**Comment by merey90** [comment]
Hey @bloodmonk7, missed your message. I already fixed it a minute ago. Sorry 😬
